apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    version: 1
    editable: false
    isDefault: true
  - name: TestData
    isDefault: false
    type: testdata
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: postgres
    password: postgres
    database: exampledb
    jsonData:
      sslmode: disable
    secureJsonData:
      password: postgres